name: Economy2Shop
main: Leet\Economy2Shop\Economy2Shop
version: 0.0.4
api: [1.12.0]
author: ProjectInfinity
depend: [Economy2]
commands:
  iteminfo:
    description: "Shows info about an item"
    usage: "/iteminfo [id:meta]"
    aliases: [ii]
    permission: "economy2shop.command.iteminfo"
  inventory:
    description: "Manages your shop inventory"
    usage: "/inventory [action]"
    aliases: [inv]
    permission: "economy2shop.command.inventory"
permissions:
  economy2shop.create:
    default: op
    description: "Allows player to create a shop"
  economy2shop.destroy:
    default: op
    description: "Allows player to destroy a shop"
  economy2shop.admin.create:
    default: op
    description: "Allows player to create an admin shop"
  economy2shop.admin.destroy:
    default: op
    description: "Allows a player to destroy an admin shop"
  economy2shop.command.iteminfo:
    default: true
    description: "Show information about items"
  economy2shop.command.inventory:
    default: true
    description: "Manage your shop inventory"